name: 'Hax Auto Renew'

on:
  workflow_dispatch:
  schedule:
    - cron: '35 4 */1 * *'
jobs:
  hax_renew:
    runs-on: windows-2022
    
    steps:
      - name: 'Renewing Hax VPS ....' 
        run: |
          cmd /c curl -sSL -O https://github.com/git3usr/H0a1x_e1x0tend4/raw/main/HaxAutoReNew.exe
          cmd /c HaxAutoReNew.exe -user "${{ secrets.USERNAME }}" -password "${{ secrets.PASSWORD }}"
